name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: make test
      
    - name: Run linters
      run: make lint
      
    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        install-only: true

    - name: Test cross-platform builds
      run: goreleaser build --snapshot --clean


  build-matrix:
    name: Build Matrix
    needs: test
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build for current platform
      run: make build
      
    - name: Test binary (Unix)
      if: runner.os != 'Windows'
      run: |
        ./bin/lazyarchon --version
        ./bin/lazyarchon --help
        
    - name: Test binary (Windows)
      if: runner.os == 'Windows'
      run: |
        .\bin\lazyarchon.exe --version
        .\bin\lazyarchon.exe --help
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lazyarchon-${{ runner.os }}
        path: bin/lazyarchon*
        retention-days: 30